//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRCorrea.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\CasaCorrea\\Sistema\\Arquivos\\")]
        public string arquivos {
            get {
                return ((string)(this["arquivos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\CasaCorrea\\Sistema\\Relatorios\\")]
        public string caminhorelatorios {
            get {
                return ((string)(this["caminhorelatorios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SERVIDOR-PC\\SQLEXPRESS;Initial Catalog=CRCFOLHA;User ID=sa;Password=A" +
            "pli5800;")]
        public string conexaosqlfolha {
            get {
                return ((string)(this["conexaosqlfolha"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=\\\\SERVIDOR-PC\\CasaCorrea\\Sistema\\Relatorios\\;Initial Catalog=RPTSQL;U" +
            "ser ID=sa;Password=Apli5800;\r\n")]
        public string conexaorpt {
            get {
                return ((string)(this["conexaorpt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\CasaCorrea\\ImagensIcones\\")]
        public string conexaoimagem {
            get {
                return ((string)(this["conexaoimagem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CARLOSCORREA;Initial Catalog=CRCDADOS;User ID=sa;Password=Apli5800;\r\n" +
            "")]
        public string conexaosqldados {
            get {
                return ((string)(this["conexaosqldados"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CARLOSCORREA;Initial Catalog=CRCBANCO;User ID=sa;Password=Apli5800;")]
        public string conexaosqlbanco {
            get {
                return ((string)(this["conexaosqlbanco"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\CasaCorrea\\XML\\Saidas\\")]
        public string SaidaXML {
            get {
                return ((string)(this["SaidaXML"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mhE0TmoicCHB5zeLTp5x6iprdj1EDvHM")]
        public string FocusNFeToken {
            get {
                return ((string)(this["FocusNFeToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.focusnfe.com.br")]
        public string FocusNFeUrl {
            get {
                return ((string)(this["FocusNFeUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ELGIN i8")]
        public string ImpressoraTermica {
            get {
                return ((string)(this["ImpressoraTermica"]));
            }
        }
    }
}
