using System;

namespace CRCorreaInfo
{
    public class clsClienteInfo
    {
        public String agencia { get; set; }
        public String alc { get; set; }
        public String andar { get; set; }
        public String ativo { get; set; }
        public String bairro { get; set; }
        public DateTime cadastrado { get; set; }
        public String cep { get; set; }
        public String cgc { get; set; }
        public String cidade { get; set; }  
        public Int32 clicontab { get; set; }
        public String clienteaprovado { get; set; }
        public DateTime clientedesde { get; set; }
        public String codigocliente { get; set; }
        public String cognome { get; set; }
        public Decimal comissaoaliquota { get; set; }
        public String comissaocomo { get; set; }
        public Decimal comissaocoordenador { get; set; }
        public String comissaopagto { get; set; }
        public String comissaopor { get; set; }
        public Decimal comissaorepresentante { get; set; }
        public Decimal comissaosupervisor { get; set; }
        public String comple { get; set; }
        public String consumo { get; set; }
        public String contato { get; set; }
        public String contribuinte { get; set; }
        public String ctacorrente { get; set; }
        public String credito { get; set; }
        public DateTime dataaprovado { get; set; }
        public DateTime datacompra { get; set; }
        public DateTime datafichafinanc { get; set; }
        public DateTime datanasc { get; set; }
        public String ddd { get; set; }
        public Int32 dependenteirrf { get; set; }
        public String descontapispasepent { get; set; }
        public String descontapispasepsai { get; set; }
        public String descontacofinsent { get; set; }
        public String descontacofinssai { get; set; }
        public Decimal desconto { get; set; }
        public String diasemana { get; set; }
        public String email { get; set; }
        public String emailnfe { get; set; }
        public String endereco { get; set; }
        public String endtipo { get; set; }
        public Int32 forcontab { get; set; }
        public String freteincluso { get; set; }
        public String freteporconta { get; set; }
        public String ftp { get; set; }
        public String homepage { get; set; }
        public String ibge { get; set; }
        public Int32 id { get; set; }
        public Int32 idaprovadopor { get; set; }
        public Int32 idbanco { get; set; }
        public Int32 idcnae { get; set; }
        public Int32 idcondpagto { get; set; }
        public Int32 idcoordenador { get; set; }
        public Int32 iddizeresnota { get; set; }
        public Int32 idestado { get; set; }
        public Int32 idformapagto { get; set; }
        public Int32 idprospeccao { get; set; }
        public Int32 idramo { get; set; }
        public Int32 idredespacho { get; set; }
        public Int32 idregimeapuracao { get; set; }
        public Int32 idrepresentante { get; set; }
        public Int32 idsupervisor { get; set; }
        public Int32 idtransportadora { get; set; }
        public Int32 idvendedor { get; set; }
        public Int32 idzona { get; set; }
        public String ie { get; set; }
        public String imunicipal { get; set; }
        public String isentoipi { get; set; }
        public Decimal limitecredito { get; set; }
        public Decimal maiorcompra { get; set; }
        public Decimal media06meses { get; set; }
        public Decimal media12meses { get; set; }
        public Decimal media24meses { get; set; }
        public String meiodetransporte { get; set; }
        public String nome { get; set; }
        public Int32 numero { get; set; }
        public String numeroend { get; set; }
        public String observa { get; set; }
        public String pais { get; set; }
        public String pessoa { get; set; }
        public String pix { get; set; }
        public String regiao { get; set; }
        public String revendedor { get; set; }
        public Decimal saldofichafinanc { get; set; }
        public String suframa { get; set; }
        public String telefone { get; set; }
        public String temfaturamento { get; set; }
        public String tipo { get; set; }
        public String tipocomple { get; set; }
        public String tiponumero { get; set; }
        public String titularcta { get; set; }
        public DateTime ultdatnf { get; set; }
        public DateTime ultdatorc { get; set; }
        public Int32 ultmednf { get; set; }
        public Decimal ultmedorc { get; set; }
        public Int32 ultnronf { get; set; }
        public Int32 ultnroorc { get; set; }
        public Decimal ultvalnf { get; set; }
        public Decimal ultvalorc { get; set; }
        public Decimal valorminimo { get; set; }
    }
}
